"""add generated by user to invoices

Revision ID: 0005_invoice_gen
Revises: 0004_catalog_map
Create Date: 2026-05-01
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0005_invoice_gen"
down_revision = "0004_catalog_map"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("invoices", sa.Column("generated_by_user_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key("fk_invoices_generated_by_user_id_users", "invoices", "users", ["generated_by_user_id"], ["id"])


def downgrade() -> None:
    op.drop_constraint("fk_invoices_generated_by_user_id_users", "invoices", type_="foreignkey")
    op.drop_column("invoices", "generated_by_user_id")
